# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./front
        run: npm install

      - name: Build frontend Docker image
        working-directory: ./front
        run: docker build -t bobapp-front .

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install backend dependencies and run tests
        working-directory: ./back
        run: mvn clean install

      - name: Build backend Docker image
        working-directory: ./back
        run: docker build -t bobapp-back .
