# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./front
        run: npm install

      - name: Run frontend tests with coverage
        working-directory: ./front
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Build frontend Docker image
        working-directory: ./front
        run: docker build -t bobapp-front .

  backend:
    name: backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install backend dependencies and generate coverage report
        working-directory: ./back
        run: mvn clean verify

      - name: Build backend Docker image
        working-directory: ./back
        run: docker build -t bobapp-back .

  sonarqube:
    name: Analyze code with SonarQube
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
